#!/usr/bin/env php
<?php

/*
|--------------------------------------------------------------------------
| Register The Auto Loader
|--------------------------------------------------------------------------
*/
require __DIR__.'/vendor/autoload.php';

/*
|--------------------------------------------------------------------------
| Create a Symfony console application
|--------------------------------------------------------------------------
*/
use Symfony\Component\Console\Application;
use Zenaton\Worker\Command\StartCommand;
use Zenaton\Worker\Command\StopCommand;
use Zenaton\Worker\Command\StatusCommand;

$application = new Application();

/*
|--------------------------------------------------------------------------
| Register commands
|--------------------------------------------------------------------------
*/

$application->add(new StartCommand());
$application->add(new StopCommand());
$application->add(new StatusCommand());

$application->run();
