#!/usr/bin/env php
<?php

require_once __DIR__.'/../../autoload.php';

use Symfony\Component\Console\Application;

use Zenaton\Worker\Command\StartCommand;

$application = new Application();

// ... register commands

$application->add(new StartCommand());

$application->run();
